### ISSUE TITLE
Propogator

### ISSUE THREAD

**Issue by ChristnSoldiers** [VoidArkMods/QoLPlus#110]
I would like to do 2 things for my server:

1 - I would like to unlock the propagator at Level 110 and be able to build it either in personal inventory or in the Fabricator.

Would like to take the Tek Replicator out of it.

What codes should I be using, and which config files should those go?

Thank you!
Uhtred

**Comment by techartguy** [comment]
> I would like to do 2 things for my server:
> 
> 1 - I would like to unlock the propagator at Level 110 and be able to build it either in personal inventory or in the Fabricator.
> 
> Would like to take the Tek Replicator out of it.
> 
> What codes should I be using, and which config files should those go?
> 
> Thank you! Uhtred

You can't simply remove the tek rep as a crafting requirement. There is no code to do that other than just spawning one in yourself.

**Comment by ChristnSoldiers** [comment]
Thank you! I truly appreciate your assistance.

I do put that in game.ini; correct?

[QOLPlus]
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_Propagator_C",EngramLevelRequirement=110,EngramPointsCost=0,EngramHidden=False,RemoveEngramPreReq=True)
EngramEntryAutoUnlocks=(EngramClassName="EngramEntry_Propagator_C",LevelToAutoUnlock=110)

This is how I have it laid out. I've got several on the server, so I am just going to let the settings go into play upon normal restart overnight.

**Comment by VoidArkMods** [comment]
Hello.
I think I answer this issue directly in a curseforge message.
These settings are expected to be in the Game.ini file, not in the GameUserSettings.ini file. They also do not expect to be under a [QOLPlus] section.
