### ISSUE TITLE
Structure Snapping Issue 

### ISSUE THREAD

**Issue by FuBz86** [VoidArkMods/QoLPlus#125]
Qol+ Storage boxes, Air conditioners, fridges and any other snapping structures from the mod no longer snap to each other. Please fix asap.

**Comment by techartguy** [comment]
> Qol+ Storage boxes, Air conditioners, fridges and any other snapping structures from the mod no longer snap to each other. Please fix asap.

have you tried uninstalling and re-installing the mod?

**Comment by FuBz86** [comment]
Yes, I have tried un-installing and re-installing to no avail, they wont snap for anyone on my server or in my singleplayer game. It was working fine when i first download it a couple of months ago. But since the last up date it has stopped working. It won't snap to foundations or eachother and you can no longer stack the small storage boxes, a/c's, fridges ect. I've tried tuning the snap points on and off with the games snapping system by holding q and i've tried using the mods snapping system with g and a mix of both.I get a notification that snapping is disabled and another when it enabled but the placement never actually changes. It apears to be stuck in free place mode. I have even tried disabling clipping and re-enabling clipping in my setting to see if that was a factor but it didn't make a difference.

**Comment by FuBz86** [comment]
@maheshphule22 
Thankyou, i appreciate the feedback. I will look into it.
