### ISSUE TITLE
Qol+ tek rep

### ISSUE THREAD

**Issue by XxStevoxX** [VoidArkMods/QoLPlus#127]
Qol+ tek rep cannot be crafted, as it requires S+ crafting Station, which does not exist for ASA.

**Comment by Tanislarnet** [comment]
It can be crafted in an existing replicator

**Comment by B4nditb04b** [comment]
No it cant im afraid. Just tried to make one in tek replicator

**Comment by aliig** [comment]
You can build a vanilla tek replicator and then convert it to a qol+ tek replicator at the converter table @XxStevoxX @B4nditb04b . I noticed its you can't craft some tek engrams though, like 2 of the 3 teleporters

**Comment by VoidArkMods** [comment]
Hello.
This issue has been fixed as part of CurseForge release 32. The QoL+ Tek Replicator can now be crafted from a Fabricator.
