### ISSUE TITLE
Qol+ Tek Replicator

### ISSUE THREAD

**Issue by Kr122b0** [VoidArkMods/QoLPlus#133]
Im trying to make the Qol+ Tek replicator but I need to craft it at Qol+ Crafting station and further down it says can be crafted at S+ Crafting station. I cant find the engram for any of those.. How do I make one? 
![image](https://github.com/VoidArkMods/QoLPlus/assets/156581507/56190974-de62-4644-ad52-e16a600ef0e8)

**Comment by VoidArkMods** [comment]
Hello!
This has been fixed as part of CurseForge release 32.
Thanks for the issue!
