### ISSUE TITLE
Tek Replicator/Dedi boxes

### ISSUE THREAD

**Issue by ThePotato6801** [VoidArkMods/QoLPlus#135]
I seem to have an issue where the QOL remote will not recognize the Replicator or the dedicated storage as a source.  Even the cloud will only pull a stack into the dedi then it just stops working. any advice or fix would be great!

**Comment by DMJayce** [comment]
I've noticed the same issue.  I was so excited to get Dedicated Storage set up, only to realize I can't use the omni-tool or cloud transfers to put material in them.  It's annoying trying to get 10k metal ingots stuffed into dedicated storage 600 ingots at a time (pulling to a vault next to them).

If the cloud pull would ignore weight limits that would be a decent workaround at least; I could pull to myself and then deposit.

**Comment by VoidArkMods** [comment]
This issue has now been fixed.
