### ISSUE TITLE
[Feature Request] QOL+ Refrigerator/Dedicated Storage

### ISSUE THREAD

**Issue by nephxio** [VoidArkMods/QoLPlus#137]
In S+, the S+ Refrigerator and S+ Dedicated Storage had the ability to store things like organic polymer, antidote, leech blood, ammonite bile, etc. Would it be possible to get versions of these implemented if it's not too difficult?

**Comment by zerafox** [comment]
The fridge can already hold these things

**Comment by nephxio** [comment]
It definitely cannot as of today

**Comment by zerafox** [comment]
> It definitely cannot as of today

Considering I'm using them to store my Organic Polymer, Leech Blood, etc;
And moved some into said structures as of today, I beg to differ.

**Comment by NobleKangaroo** [comment]
Original (vanilla) refrigerators cannot - and have never been able to - hold organic polymer, ammonite bile, leech blood, or the oil with a timer. The only thing they can hold is bio toxin. This, in addition to 100 storage slots instead of 80, was the benefit of using QOL+ (S+) refrigerators.

**Comment by penash42** [comment]
I think what zerafox is saying is the QoL+ fridge already exists in the mod and can hold all the things listed.  The fridge was added to the mod back in November.

**Comment by nephxio** [comment]
I stand corrected about the QoL Refrigerator :)  Dedicated storage would be awesome still if you can fit it in, but I know you're a busy person!

**Comment by VoidArkMods** [comment]
The QoL+ Dedicated Storage (+ intake) is reaching the top of the priority list now, it will likely be the next thing I'll work on.

**Comment by VoidArkMods** [comment]
I did a first attempt at those, very early (around the same time the metal storage got released), but unfortunately most of the models do not behave properly in ASA. I'm far from a pro with models/mesh, so it may take some time!

**Comment by VoidArkMods** [comment]
I prefer to not maintain a Discord server. As I mentionned on some other issues, I do not plan on making any paid mod or living from modding, it's just a hobby. I need to find a better solution to communicate on update though, because GitHub's issue tracker is not expected to be used that way. I'll figure out something!

**Comment by xxxDarksidexxx** [comment]
Would it be possible to add Bulk Storage boxes to QoL to enable pulling from them?

**Comment by VoidArkMods** [comment]
From the mod description of Bulk Storage, the dev may have based his structures on the optimized ASA dedicated storages, which is the reason the pulling and omni-tool does not work with them.
Hopefully, the additions and fixes with dedicated storages on QoL+ will naturally fix these issues.

**Comment by xxxDarksidexxx** [comment]
That would be huge! 

Trying to move on from AA, Bulk Storage allows full wireless crafting and has Intake and Autosorter. However, QoL+ would help with those crafting tables, which are not wireless enabled... So having those boxes visible, would help tremendously with that task.

**Comment by VoidArkMods** [comment]
QoL+ Dedicated Storages are now available (CurseForge build version 34)
