### ISSUE TITLE
Propagator doesn't recognize mutations

### ISSUE THREAD

**Issue by TheBrandonG** [VoidArkMods/QoLPlus#138]
So basically as the title says. I've made it to the point in my server that i can start using propagators and their function works for all intents and purposes but at this point ive already got 9 mutations on my carcha. When i put that mutated male in the propagator the propagator recognizes those mutations but doesnt pass the actual stats on to the baby when i breed so I instead get a baby that says it has 10 mutations now but its only getting one of them added to its stats and the rest are useless. the original mutated carcha father and a baby from the propagator shown below for reference. You can see the melee on the baby doesnt actually calculate all 10 mutations and is only counting the one it gained in the propagator

![image](https://github.com/VoidArkMods/QoLPlus/assets/138073562/455f610b-c5ff-4ba4-b694-b9425367cc06)
![image](https://github.com/VoidArkMods/QoLPlus/assets/138073562/3ce38da3-b037-430a-b068-5c1ec9e2c978)

**Comment by VoidArkMods** [comment]
Hello!
@BlownBigBen is right: the Propagator used to trigger the mutation on the wild level, not on the mutation stack. That's how it was done in ASE. The CurseForge version 32 of the mod (released the 23rd of January 2024) fixes that: the Propagator now mutates on the mutation stack, not on the wild level anymore.
