### ISSUE TITLE
New update (23 Jan 2024) QOL+ structures all not placeable

### ISSUE THREAD

**Issue by NobleKangaroo** [VoidArkMods/QoLPlus#147]
QOL+ structures can be crafted or converted but when attempting to place them (either through hotbar activation or via inventory "equip"), nothing happens. This has been the case for a few structures (vault for instance) but now it's affecting every QOL+ structure.

Tested this on the server I normally play, in single player, and on a brand new fresh test server. Results are all the same.

If not fixed, this pretty much puts the nail in the coffin for the mod.

**Comment by NobleKangaroo** [comment]
> Hello. This issue cannot be reproduced. Usually, this happens when the mod is not installed properly. Please, make sure to install the mod properly, both server-side and client-side if applicable.
> 
> Closed as not planned (can't repro)

The server I'm playing has removed the mod and reinstalled it and the issue remains for all users.
I set up a new server and the issue is present.
Single player, installing the mod through the ingame installer, the issue is present.

How are you installing the mod?

**Comment by VoidArkMods** [comment]
The issue has been closed, as this could not be reproduced, is a common issue that happen on every mod, and that a couple minutes on any search engine can help fix.

On a dedicated server, the mod installation is located here: C:\path_to_server_install\ShooterGame\Binaries\Win64\ShooterGame\Mods\83374\939228_5052746. Shut down the server, browse here, delete the QoLPlus folder in it, restart the server.
On a client, the mod installation is located here: C:\Program Files (x86)\Steam\steamapps\common\ARK Survival Ascended\ShooterGame\Binaries\Win64\ShooterGame\Mods\83374\939228_5052743. If you installed the game in a different folder, please adapt the path. Close the game, browse here, delete the QoLPlus folder in it, start the game. You can then either download the mod manually from the mod management section of the game, or join a server that has the mod installed properly. Keep in mind that, when the client and the server version of a mod mismatch, the server version will be downloaded on the client, therefore if the mod is invalid on the server side, it will distribute the invalid version when attempting to join.

I have re-retested the version change of today, both in SP and on a dedicated server, I confirm the issue cannot be reproduced.

**Comment by NobleKangaroo** [comment]
Thank you very much for taking the time to reply. I had to actually fully delete the mod folder which I didn't realize wasn't removed on reinstall.

Keep up the great work!
