### ISSUE TITLE
Donation page?

### ISSUE THREAD

**Issue by NobleKangaroo** [VoidArkMods/QoLPlus#150]
I'd be personally interested in sending you a few bucks for your work, and I know others are likely as well. I know you're not looking into making it a paid thing but if you'd allow us to express some gratitude in that regard, I'm sure folks would appreciate the opportunity to send some thanks for your work on this mod.

**Comment by VoidArkMods** [comment]
Hello!
I appreciate the intention, that's very kind! The thing is, I really do not need that money, it's better for you to keep it. There are other ways to show gratitude, using the mod means already a lot to me!

**Comment by NobleKangaroo** [comment]
👍 Thanks again.
