### ISSUE TITLE
BluePrint Paths

### ISSUE THREAD

**Issue by BeatleGold** [VoidArkMods/QoLPlus#151]
Hi I would like to find out if there is a blueprint path because I want to remove some engrams.

I know this was asked in another thread but I can['t view it because it marked as completed.

**Comment by VoidArkMods** [comment]
Hello!
Another user kindly contributed this list of engrams, at the root of the project: https://github.com/VoidArkMods/QoLPlus/blob/main/EngramEntries
If some are missing, then they are probably available in the source code. Items/structures are usually located under the "Misc" folder, with the exception of some crafting stations which are under "Crafting". As new structures are being incorporated, I'll do my best to make the engram list file stay up-to-date.
