### ISSUE TITLE
QoL+ Dedicated Storage and Intake engrams not unlockable

### ISSUE THREAD

**Issue by NutroxModding** [VoidArkMods/QoLPlus#154]
Hey, it seems like I cant unlock the QoL+ Dedicated Storage and Intake engrams. They are not in the list of the engrams. I tested it on our Server and in the Singeplayer. I already reinstalled the mod.

![Bild_2024-01-28_205134420](https://github.com/VoidArkMods/QoLPlus/assets/79375080/eca231be-9f94-43b8-958c-9f0aff5519ed)

**Comment by NutroxModding** [comment]
OK it seems like version 34 is not the one the server downloaded because Curseforge still has 33. So I just got jebaited by your patchnotes and our server showing an update for the mod XD

**Comment by VoidArkMods** [comment]
Hello!
I confirm, the build with QoL+ Dedicated Storages (+ Intake) is still under review. As the version 33 got approved late today and I published to review 34 right after, this might take a couple of days. Sometimes it can take a full week.
I updated the mod's page on CurseForge with the most recent patchnotes, with a mention that the build 34 is still under review.
