### ISSUE TITLE
Spawn codes

### ISSUE THREAD

**Issue by xxnightwingxx52** [VoidArkMods/QoLPlus#158]
I have been looking for the spawn codes to be able to spawn or giveitem propagator

**Comment by xxnightwingxx52** [comment]
or if there is a way to change the level of the engram for the propagator to 105

**Comment by VoidArkMods** [comment]
Hello.
Regarding the list of PrimalItem to use the giveitem command, currently it's not listed anywhere but you can browse the code's hierarchy and use it to build your command to your needs.
For the propagator override, the EngramEntry list is actually available at the root of the source code repository, kindly contributed by a user. The server configuration to remap engrams is available on the official Ark wiki. I remember having answered that in another issue too, so you might find it here as well.

**Comment by xxnightwingxx52** [comment]
I'm sorry i'm new to this how do i browse the codes hierarchy

**Comment by VoidArkMods** [comment]
There is a "Code" tab at the top of this page. When you go to it, you can see the source code of the mod. It's organized in folder, most of the structures are inside the "Misc" folder. You want to look for files that start with "PrimalItemStructure_" in their name, then you can reproduce the path you take to get to the file into your giveitem command.
