### ISSUE TITLE
[request]Display what items are missing on a failed pull

### ISSUE THREAD

**Issue by nephxio** [VoidArkMods/QoLPlus#16]
Hi folks! Thanks for porting this to ASA!

In the old ASE version of S+, if you had a recipe (let's arbitrarily say 20 wood, 15 thatch, 5 raw metal), and you were short any items when you tried to pull for a craft, it'd display how many of each item you're short. The mod doesn't appear to do that currently. 

Steps to reproduce:
1) Select any engram and make sure you're short material(s) for it
2) Hit the pull for craft button
3) Observe there is no notification that you're short materials. The pull just silently fails.

Thanks everyone!

**Comment by VoidArkMods** [comment]
Hello!

As far as I tested, the notifications are properly triggered in single player but not in multi player. They have been wired and should be working, but there seems to be a replication issue for multi player. I'm working on that.

Thanks for raising the issue!

**Comment by VoidArkMods** [comment]
Fixed as part of CurseForge release 12.
