### ISSUE TITLE
Pulling stuff for a crafting recipe creates angler gel

### ISSUE THREAD

**Issue by Polizeiwaschbaer** [VoidArkMods/QoLPlus#183]
Don't ask me, im just as confused as you.

Basically, whenever I pull something for a crafting recipe, it replaces some kind of ressource (f.e. hide when crafting flak) with AnglerGel. Normal pulling works just fine.
 I am playing on the server with other people, but it pretty much affects just me. We do have Visual Storage (Project ID on CurseForge: 935528) on the server and I'm the only one using it, so I suspect that's the cause. I don't know if it just converts ressources into gel or just dupes it, gotta try that out.

Imma try and remove all the VS structures to see if it changes anything
I'll keep this updated

**Comment by Polizeiwaschbaer** [comment]
Edit 27/02
Removing the VisualStorage structures seems to fix the problem, compatibility error I guess?

**Comment by VoidArkMods** [comment]
Hello!
You said in the first message that the problem happens only for you and not for other players on the same server. This seems to hint at a mod corruption.
I suggest you to do a clean delete and reinstall of both mods (QoL+ and VisualStorage). On console, you can find the mod on the mod management UI and delete them, then re-install them. On PS5, there are a lot of mod corruptions and weird behaviour when installing mods. It should not happen there, as it seems to have higher chances of happening with big mods, but to put all chances on your side you can uninstall the mod, completely close the game, restart it and re-install the mod.
On PC, you can browse to your mods' folder and delete both folders for QoL+ and VisualStorage, then reinstall them manually from the game.

**Comment by Auranim** [comment]
If I may. I use both mods and have had this problem. This only happens when the items you're trying to pull are in your dropbox/crane. Adding them to the appropriate storage container fixes the issue (or, rather, prevents it from ocurring).
