### ISSUE TITLE
Primal Item Path

### ISSUE THREAD

**Issue by Arceu80** [VoidArkMods/QoLPlus#185]
Hello, does anyone know the primal item path for the propagator, or is there a list available for those in the mod?

I'm aware there's a list with the engram entries, but I need the complete blueprint.

Thanks

**Comment by VoidArkMods** [comment]
Hello!
For now no, there is no list of PrimalItem for now. I will document them at some point.
You can still get the information if you want it, though: from the "Code" tab, type "PrimalItem" in the "Go to file" search bar, it should list all of them. The full path should be the path to the file, with a / at the beginning. For example, for the QoL+ Air Conditioneer, it should be "/QoLPlus/tree/main/Misc/AC/PrimalItemStructure_AirConditionerPlus". Some commands like "giveitem" would expect a repetition of the PrimalItem at the end, after a dot (/QoLPlus/tree/main/Misc/AC/PrimalItemStructure_AirConditionerPlus.PrimalItemStructure_AirConditionerPlus).
Note that it's only theory, I can't test it for now, the computer is being repaired :(

**Comment by Arceu80** [comment]
Thanks, its works!
 cheat GiveItem "Blueprint'/QoLPlus/Misc/Propagator/PrimalItemStructure_Propagator.PrimalItemStructure_Propagator'" 1 1 false
