### ISSUE TITLE
QOL+ Tek Trough showing as empty when full.

### ISSUE THREAD

**Issue by HeyKrystal** [VoidArkMods/QoLPlus#190]
When you are filling a QOL+ Tek Trough with food, the model still shows as if it is empty. The QOL+ Non-Tek Trough works fine, and the Vanilla Tek Trough works fine.

Attached image is of QOL+ Tek Trough (Left) vs. Vanilla Tek Trough (Right). They both have food in them.

![ARK  Survival Ascended Screenshot 2024 03 05 - 22 24 02 46](https://github.com/VoidArkMods/QoLPlus/assets/5586868/2a8b76e0-4472-4d06-9628-7938a2591ae3)

**Comment by VoidArkMods** [comment]
Hello!
The QoL+ Tek Trough is not officially supported as of now: there is to engram to craft it directly. I assume you got one by converting a vanilla item with the QoL+ Converter.
I note that there will be an issue with the visual cue and will fix that before adding the QoL+ Tek Trough properly into the mod, thanks for the feedback!

**Comment by HeyKrystal** [comment]
Oh gotcha, I did not realize that. Thanks for the update!
