### ISSUE TITLE
Error message: "Crafting requirements do not match"

### ISSUE THREAD

**Issue by valchiara** [VoidArkMods/QoLPlus#197]
Trying to convert Vanilla foundations gives me an error message "Crafting requirements do not match". I have not changed any crafting costs.

**Comment by VoidArkMods** [comment]
Hello.
As stated on the curseforge page, QoL+ will not have foundations, therefore you cannot convert from a vanilla foundation to a QoL+ foundation or vice-versa.
Are you using a QoL+ converter to try to convert to a structure of another mod?
