### ISSUE TITLE
Multitool blacklist

### ISSUE THREAD

**Issue by zerafox** [VoidArkMods/QoLPlus#20]
I've also attempted to disable part of the MultiTool, but the setting doesn't seem to work no matter what I've tried:

MultiToolBlacklist='Dino'

MultiToolBlacklist=Dino

Neither seem to disable the function of any of the Dino setting options on the Multi-tool

**Comment by VoidArkMods** [comment]
Good day!

The issue has been reproduced. The fix will be available in the next version.

Thanks for the feedback!

**Comment by VoidArkMods** [comment]
Fixed as part of CurseForge release 12.
