### ISSUE TITLE
Crossplay compatibility 

### ISSUE THREAD

**Issue by ReapersWrath** [VoidArkMods/QoLPlus#21]
Will this mod be avaliable for the console crossplay servers when it they release it. Im trying to only add mods that will be avaliable then because i will be switching to a crossplay server

**Comment by zerafox** [comment]
I sure hope so because this was the last vital missing piece for our server and we plan to go Crossplay as soon as all our mods update.
If there's no plans to update this one we'll be forced to make a very hard decision.

**Comment by VoidArkMods** [comment]
The goal is to be crossplay. Yet, due to the amount of content and the requirements for console mods, it might take a bit of time initially to be compatible. It will be high on the priority list for sure!

**Comment by VoidArkMods** [comment]
QoL+ is now cross-platform, from CurseForge release 14 and upward.

**Comment by ReapersWrath** [comment]
Thank you for the update!!
