### ISSUE TITLE
New berries (Magenberry, Verdberry, Cianberry) and Resin aren't visible in the pull list.

### ISSUE THREAD

**Issue by VoidArkMods** [VoidArkMods/QoLPlus#23]
The new items from ARK SA, as well as some fresh resources, are not known by the mod. They can't be pulled, nor managed from the OmniTool.

**Comment by zerafox** [comment]
If you're talking about like say the Verdberries, Magenberries and Cianberries, I've been moving them around with the omni-tool left and right since we installed this mod to our server.

**Comment by VoidArkMods** [comment]
Yes, it's about these 3 berries and the Resin. They are not listed on the resource list, but the basic transfer from the OmniTool is able to move them around, as it's just reading an inventory and moving it somewhere else without trying to understand more in depth details about the items being moved.

The fix will be available in the next release.

**Comment by VoidArkMods** [comment]
Fixed as part of CurseForge release 12.
