### ISSUE TITLE
Engram Whitelisting missing several entries

### ISSUE THREAD

**Issue by techartguy** [VoidArkMods/QoLPlus#30]
I noticed in the files manifest that there was an engram override entry already. We use a whitelist on our ASA server since we run the arkitect mod so I have removed all the vanilla entries. I went through and added the substitution equivalencies in the engram menu but they do not show up (refining forge, cooking, pot, smithy, etc) Nor does the base crafting station show up either. 

Possible conflict with having our own whitlist?

**Comment by VoidArkMods** [comment]
Hello!
The QolPlusEngramWhitelist ini setting behaves the same way it behaves in S+: it deals only with the modded items and has no impact on the vanilla engrams. However, there is an ini setting inherited from S+ that has a potential impact on vanilla engrams: EnableEngramOverride. It is false by default, but if you copied over your setting from SE it might be true for you. This will try to override the vanilla structures with their QoL+ counterparts, and they happened to be pre-available in the mod (but not referenced, so impossible to craft legitimately nor place in the game). That might be one explanation.

To make sure the issue does not come from QoL+, you can reference vanilla engrams in this ini setting: EngramOverrideBlacklist (for example: EngramOverrideBlacklist=EngramEntry_Fabricator_C,EngramEntry_Grinder_C). It will prevent any override to happen on these engrams.

**Comment by techartguy** [comment]
At present I had not imported any ini settings from the gus so it was running at defaults save for the engram overrides I had done pulled from the manifest list. Was only testing the engram menu exclusively before proceeding to any ini configuration. A few do show up but not many. OverrideNamedEngramEntries=(EngramClassName="EngramEntry_IndustrialGrillPlus_C",EngramLevelRequirement=50,EngramPointsCost=40,EngramHidden=False,RemoveEngramPreReq=False)

For instance is one of the entries that does not work. Simply replaced the vanilla class with the QoL+ class

**Comment by VoidArkMods** [comment]
It's likely that only engrams that are activated by the mod can be properly overriden. In the example you provided, you try to manipulate the IndustrialGrillPlus, which has not be linked properly in the mod (it does not point to a valid structure to place, but the engram exists in the mod). I assume supported capabilities will work, like the Nanny or the various storage boxes.
The few engrams that are properly mapped at this point are the ones referenced on the mod's CurseForge page. A user contributed recently a file that contains all of them: https://github.com/VoidArkMods/QoLPlus/blob/main/EngramEntries

**Comment by techartguy** [comment]
It's possible, I selected a few options as a test with the most sought-after items I was originally looking at it for.

The ones below out of the list did show up
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_Nanny_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_Gardener_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_Farmer_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_BeeHivePlus_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_AmmoBoxPlus_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_FeedingTroughPlus_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_AirConditionerPlus_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_StorageSmall_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_StorageMetal_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_StorageLarge_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_StandingTorchPlus_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_WallTorchPlus_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_OmniTool_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_SplusMultiTool_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_Propagator_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_HitchingPost_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_BlueprintMaker_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)

These did not show up, much the same like vanilla structure replacements before hand. 
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_SPlusCraftingStation_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_SprayPainterPlus_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_CloningChamberPlus_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_HarvesterPlus_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_Hatchery_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_ItemAggregator_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_MultiLamp_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_StarterBlock_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_TransferControlUnit_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_TeleporterPlus_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_ElevatorTrack_Metal_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_ElevatorPlatform_Large_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_ElevatorPlatform_Medium_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName="EngramEntry_ElevatorPlatform_Small_C",EngramLevelRequirement=1,EngramPointsCost=3,EngramHidden=False,RemoveEngramPreReq=False)

**Comment by VoidArkMods** [comment]
It confirms my assertion: only the engrams that are linked in the ModAssetData can be manipulated that way. It's expected behaviour for me, as I can't provide support on the other engrams.

Regarding the propagator, I saw a couple mods that seem to not map the gender of creatures properly. Using the Wildcard-provided cryopods in the devkit, I can confirm that the propagator distinguish the gender as expected. The SCS mod is mapping the gender properly, so that's a valid alternative if you want. In essence: this is not an issue with the propagator.
