### ISSUE TITLE
Dedi Storages?

### ISSUE THREAD

**Issue by zerafox** [VoidArkMods/QoLPlus#34]
Do you plan to add Refrigerated Dedicated Storages at some point as well?

It'd be nice to have a list of features you plan to port over (as this would probably be shorter than ones you don't).

**Comment by VoidArkMods** [comment]
Hello!
The dedicated storage used to be a thing in S+ and I plan to port them, but I want to do it the proper way. To do that, I will need some time to find the right way to interact with dedicated storages. But be sure they are high on the priority list!

**Comment by zerafox** [comment]
I'm not sure who's doing what on what end here but I'm sending this in to both of you.

We're using Klinger's Additional Structures on our server:
https://www.curseforge.com/ark-survival-ascended/mods/additional-dedicate-storage

It adds early game Dedicated Storages, which I'm not certain how he's handling these. QoL will pull flawlessly from the Vanilla Tek Dedicated storages in all our testing, however when it comes to Klinger's dedicated storages it will say it's pulling but ultimately nothing happens.

**Comment by zerafox** [comment]
I will try to keep you updated with what I hear from Klinger as well, I've asked if he's just reused the inventory function or he's gone and made his own or whatever.

Thank you for the quick reply!

**Comment by VoidArkMods** [comment]
He probably knows it already, but you can give him the link I posted before, as it captures precisely how Vanilla dedicated storages are working and the implications it has on the code.

**Comment by VoidArkMods** [comment]
QoL+ Dedicated Storages are now available (CurseForge build version 34)
