### ISSUE TITLE
Performance drop after installing

### ISSUE THREAD

**Issue by Remp2012** [VoidArkMods/QoLPlus#36]
Before I added this mod to my server i was getting 60-70 frames, after I'm getting 30-50 and when I open a door it drops further.

**Comment by Remp2012** [comment]
And it not right away, its over a period of 20 or so min and it keeps dropping. If I relog it starts over again

**Comment by Remp2012** [comment]
Correction: It might have been an issue with another mod Klinger Additional Structures

**Comment by VoidArkMods** [comment]
Hello!
That would have been surprising if QoL+ was messing with doors, as all code related to doors has been removed from the released artifacts. I will close the issue, feel free to re-open it if you can pinpoint that it's QoL+ that is causing serious performance drop.
