### ISSUE TITLE
No QoL+ engrams after update

### ISSUE THREAD

**Issue by KyllayBW** [VoidArkMods/QoLPlus#41]
After uploading today's update to the server, all engrams from the mod disappeared 

Uploading ARK SA 11-26-2023 20-02-18-565.mp4…

**Comment by VoidArkMods** [comment]
Hello!
It looks like the video did not upload, I can't see the capture.
The mod got released today and is available from CurseForge. It is expected to be functional and retrocompatible. We tested that multiple times on multiple servers. Can you make sure the mod is still listed in the mods list? Do you use the startup options "-ServerPlatform=PC" and/or "-pconlymods"?

**Comment by KyllayBW** [comment]
https://github.com/VoidArkMods/QoLPlus/assets/152094730/dc4a73dd-ceec-464f-a4b6-9a3f1dbe4355

I'm try this startup options

**Comment by VoidArkMods** [comment]
Oh, so you can still craft them, but they do not appear on the engram unlock list! That's a nice one. It doesn't seem related to the mod itself though. You can try to re-upgrade your server and manually update the mod from the game menu on the client side (the expected mod version is 14

**Comment by KyllayBW** [comment]
I don't know what happened, but reinstalling the game server helped

**Comment by VoidArkMods** [comment]
It's probably CurseForge's servers that have a hard time delivering the mod updates. I'll close the issue, you can re-open it if the issue reappears.
