### ISSUE TITLE
QOL+ Multi-Tool 

### ISSUE THREAD

**Issue by ReturnoftheMaQ** [VoidArkMods/QoLPlus#43]
GG geting out a reliable mod folks, and well done on a quick turn around for Xplay. loved being able to open our servers to XBOX & Windows.

Just some feed ack on the Multi-tool

Again haven't tested thorouhgly but a consistent occurance when the multitool is equiped  

The gun highlights via a pulse wild dinos not just visible onesbut also wild dinos through, the Map, structures, water and resources
No complaint here, just providing hopefully positive feedback to able you guys to tweak the mod and polish it off

Thank you for a great QOL mod and keep up the great work

**Comment by VoidArkMods** [comment]
Hello!
This is a duplicate issue of #32 , but just to keep you updated I hopefully found a fix for that. It will be shipped in the next release!

Regards

**Comment by ReturnoftheMaQ** [comment]
> Hello! This is a duplicate issue of #32 , but just to keep you updated I hopefully found a fix for that. It will be shipped in the next release!
> 
> Regards

Amazing, really apprciate the work you guys have done for the community.  And thank you for the reply too really nice touch! 

GG team!!

**Comment by VoidArkMods** [comment]
This issue has been fixed now, the fix is available publicly for all platforms!
