### ISSUE TITLE
Propagator bugs

### ISSUE THREAD

**Issue by techartguy** [VoidArkMods/QoLPlus#46]
Bug 1) Removing or adding any crypods to the propagator while it's active disables the Structure's UI interactions. 

Bug 2) Propagator is not passing mutations on to the offspring from the parent.

**Comment by VoidArkMods** [comment]
Ah, bug3 is not of my doing :D The cryopods from wildcard (available in the devkit directly) identify the gender properly, and mods who extend the cryopod the same way make the propagator detect the gender correctly as well. I know that some cryopod mods do not store the gender properly, but some do. If that's a bother, then please consider reaching out to the mod author, or changing cryopod mod.

**Comment by techartguy** [comment]
> Bug 2) Propagator is not passing mutations on to the offspring from the parent. -This is a visual glitch shown on the egg but when hatched they show in ancestors and the mutated stat is accurate.
> 
> Bug 3) Propagator does not correctly identify male vs female. I found that even males (most of the time) register as female on the breeding screen and costs 1 element to mate even though it a male and on the male side of the breeding.

I see, also the logic for the propagator import is that still using the old ase code? Since movement speed isn't a thing on ASA that mutation should probably be nixed.

**Comment by VoidArkMods** [comment]
As the bug number 1 is tracked in another issue, bug 2 is now fixed and bug 3 is not directly related to the mod, I'll close the issue.
