### ISSUE TITLE
[NewRequest] QOL+ cooker with auto cooking without colors;

### ISSUE THREAD

**Issue by maheshphule22** [VoidArkMods/QoLPlus#48]
Nice job having mod working <3

Vanilla cooker cooks colors from berries when we have auto cooking enabled, and if we disable it we can only craft recipes 10 items at a time.
So requesting cooker similar to s+ cooker which had different options for auto cooking only recopies and not colors. And different option for auto cooking colors.

**Comment by nephxio** [comment]
Autocook drives me *bananas*
