### ISSUE TITLE
Crop Plots will not place

### ISSUE THREAD

**Issue by DyasAlure** [VoidArkMods/QoLPlus#55]
I can place crop plots on foundations, but i can not place them on ceilings. Use case: I have my green house over water with a water base. I could not place the large crop plots, so i looked around, and found i could place on a foundation, but not a ceiling.

**Comment by VoidArkMods** [comment]
Hello!
QoL+ does not have custom crop plots yet, nor foundations/ceiling. The issue you are describing related to the base game :D

**Comment by DyasAlure** [comment]
omg, i feel dumb. sorry, i did in fact follow the wrong mod. I am so sorry again. I love the parts i have tried of QOL+.
