### ISSUE TITLE
Allow admins to disable to disbale sub settings

### ISSUE THREAD

**Issue by Spencer021** [VoidArkMods/QoLPlus#65]
The "ESP" for structure mode is OP, But the only way to disable it is to disable the entire "structure" setting. But that also disabled the "pickup" settings.

**Comment by VoidArkMods** [comment]
Hello.
This is a duplicate issue, other users already created an issue about the ESP on the multitool. This is being fixed in the next update, assuming CurseForge lets me cook it.
