### ISSUE TITLE
air conditioner sound

### ISSUE THREAD

**Issue by pyrowknight** [VoidArkMods/QoLPlus#69]
so in the info it say that the air conditioners are silent but mine are not they are very loud

**Comment by AtreyuStraywolf** [comment]
Almost all the structures that say are silent make noise. Grinder, Air Conditioner, Fabricator. They didn't before.

**Comment by VoidArkMods** [comment]
Hello.
This can not be reproduced: these structures do not make sound, even after the recent big update from Wildcard. Are you sure you do not have the `EnableStructureSound` INI setting set to true?
