### ISSUE TITLE
Way to disable each individual engram in the ini or at least an official list of engrams (to disable using OverrideNamedEngramEntries)?

### ISSUE THREAD

**Issue by DavidRehm** [VoidArkMods/QoLPlus#7]
[easy] Can we get an official list of all QoLPlus engrams so server admins can enable/disable each specific engram/feature (using OverrideNamedEngramEntries)?

[more work] Longer term, can we get a way in the QoLPlus config ini to enable/disable each specific engram/feature without having to use the laggier OverrideNamedEngramEntries method?

**Comment by VoidArkMods** [comment]
Hello!

It is planned to list all engrams directly on the README, but for now you can have a look at the code itself to see the exact name of the EngramEntry asset for a specific item. Keep in mind only a few of them are currently tied to the mod (the ones that are listed on the mod page on CurseForge).

Some features are already tied to an ini configuration, but it's true some of them are not. When the times come to focus on performances, it's a good idea.

**Comment by VoidArkMods** [comment]
The available engrams have been listed in a dedicated file at the root of the repository. They can be used in order to leverage Wildcard-provided server settings to manipulate engrams.
