### ISSUE TITLE
Crossplay?

### ISSUE THREAD

**Issue by Tobeey1993** [VoidArkMods/QoLPlus#75]
I haven't read any information. Is the mod crossplay compatible?

**Comment by garrowson** [comment]
We have players on Playstation joining the server

**Comment by VoidArkMods** [comment]
Hello!
This is a duplicate of a couple other issues already opened by other players. The mod is fully crossplay, I tested all platforms personally. The mod will not drop cross-platform support: it will lead to slower releases (each PS5/Xbox release requires a review that can take up to one week), but I commit on never forcing servers to go back to PC only, even temporarily.
