### ISSUE TITLE
New Item: Dedicated Storage/Intake

### ISSUE THREAD

**Issue by iDiffusion** [VoidArkMods/QoLPlus#94]
Would you be able to add dedicated storage and dedicated storage intake to ASA? We miss having these in and the normal dedicated storage boxes suck. I have to say I'm spoiled, having to place all the items into the vanilla dedicated storage boxes is tedious, and they don't take any perishables. The old one (s+) would take any item that was able to be pulled, would you also follow this?

**Comment by AtreyuStraywolf** [comment]
I Also would like to see this added. As well as the aggregator. And maybe the silent generators.

**Comment by VoidArkMods** [comment]
QoL+ Dedicated Storages are now available (CurseForge build version 34)
