### ISSUE TITLE
Unable to transfer to TEK Dedicated Storage using QOL+ Omni Tool

### ISSUE THREAD

**Issue by NobleKangaroo** [VoidArkMods/QoLPlus#97]
Hello,

First off I'd like to say that this mod is a LIFESAVER. It's been so much easier to transfer items than walking them around and yeeting bags everywhere, and the profiles per tool are great. That said, many have encountered issues with the QOL+ Omni Tool (both in basic and advanced mode) being unreliable when working with TEK Dedicated Storage.

If you start with an empty TEK Dedicated Storage (or empty the TEK dedicated storage and clear its resource type) and transfer items, all items are able to be transferred at once and it displays "QOL+: _$STACK_COUNT_ items transferred." Similarly, withdrawing one or more items FROM the TEK Dedicated Storage to another destination, for instance the player or a vault, works as intended. However after this initial deposit, and subsequent designation of the TEK Dedicated Storage's resource type, the QOL+ Omni Tool begins behaving erratically.
![image](https://github.com/VoidArkMods/QoLPlus/assets/34781835/9cd30910-5d5a-48a3-b45e-3bf74b38fece)

I think I've diagnosed the symptom as either a math issue, or an issue with how QOL+ handles numbered storage (versus item stack storage containers). Essentially, any time that a numbered storage (for instance the TEK Dedicated Storage) is deposited to, QOL+ fails to transfer the items to the numbered storage container and displays a message "QOL+: Transferred _(the amount you're transferring minus the stack size, as a negative number)_." For instance, if you had 83,113 wood in a TEK dedicated storage and try to transfer more, a message "QOL+: -82,813 items transferred." is displayed, but no items are transferred. This number is 83,113 (items already in target container) minus 300 (stack size), flipped to a negative number (-82,813).
![image](https://github.com/VoidArkMods/QoLPlus/assets/34781835/b76ee337-e60e-460c-ad66-73938e9ec097)

Similarly, when transferring the entire content out of TEK Dedicated Storage to another target (say a vault or dino), the numbers don't refresh on the TEK Dedicated Storage container properly. It takes a manual update (depositing an item, withdrawing it back out) to force the TEK Dedicated Storage container to display a count of 0 and be treated as actually empty.

It feels like there's either something going wrong in how QOL+ is handling numbered storage, or something wrong with TEK Dedicated Storage itself, but I really don't know how to even begin testing this hypothesis as I've never dug into Unreal or the innerworkings of ARK mods. Hope to see this fixed if it's a QOL+ thing but if not, hopefully we will see QOL+ dedicated storage that fixes it in the future.

Thanks again for an awesome mod!

**Comment by VoidArkMods** [comment]
Pulling from/to dedicated storages should now be fixed (at least for vanilla and QoL+ ones).
